### ISSUE TITLE
Error: Something went wrong, please check your settings

### ISSUE THREAD

**Issue by manjump** [linuxserver/docker-duckdns#58]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,
I install docker swag and docker duckdns because I use duckdns.org. But in log of container duckdns:

Something went wrong, please check your settings Sun Mar 19 14:27:48 CET 2023
The response returned was:
KO

`version: "2.1"
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=998
      - PGID=100
      - TZ=Europe/Paris
      - SUBDOMAINS=wildcard
      - TOKEN=xxxxxxxx
      #- LOG_FILE=false #optional
    volumes:
      - /srv/dev-disk-by-uuid-17502927-065b066-8f35344387d4/Storage/appdata/duckdns/config:/config #optional
    restart: unless-stopped`

### Steps To Reproduce

immedialtly after update the stack

### Environment

```markdown
- OS:linux x86_64 Debian GNU/Linux 11 (bullseye)
- How docker service was installed:stack in portainer
```

### CPU architecture

x86-64

### Docker creation

```bash
stack in portainer
```

### Container logs

```bash
Something went wrong, please check your settings Sun Mar 19 14:33:59 CET 2023
The response returned was:
KO
Something went wrong, please check your settings Sun Mar 19 14:39:37 CET 2023
The response returned was:
KO
Something went wrong, please check your settings Sun Mar 19 14:41:15 CET 2023
The response returned was:
KO
```

**Comment by aptalca** [comment]
I doubt your duckdns domain is `wildcard`

**Comment by manjump** [comment]
Thanks a lot aptalca:
`SUBDOMAINS=xxxxxx #xxxxx.duckdns.org`
works

**Comment by sameleff** [comment]
I'm experiencing the same issue now and can't seem to resolve it. I've been using this duckdns container alongside the linuxserver/swag instance for months successfully, using a wildcart cert for a duckdns domain. Earlier today, I received a new public IP address, and now my proxy isn't working. I updated the `current ip` field after logging into duckdns, but this still didn't resolve the error thrown by this duckdns service. @manjump, did you enter your subdomains exactly as you typed them (assuming that xxxxxx was replaced with your actual domain)...meaning you used `#` to indicate a request for a wildcard cert rather than a `*`?
