### ISSUE TITLE
[FEAT] (Not Completed) healthcheck to be added to docker-compose

### ISSUE THREAD

**Issue by LostOnTheLine** [linuxserver/docker-duckdns#59]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

I addition to the docs on how to add a heathcheck to the docker-compose that would check the current IP of one of the IPs in the SUBDOMAINS variable & check if it is the same as the current WAN IP
```
        current_ip=$(curl -s https://icanhazip.com)
        duckdns_ip=$(nslookup $SUBDOMAINS.duckdns.org 8.8.8.8 | awk '/^Address: /{print $2}')
```

& determine if the IP is the same.

A Simple healthcheck If the IPs are the same the container is healthy, if not the container is not working. 

### Reason for change

The container has no healthcheck,

**Comment by aptalca** [comment]
As an org, we don't add healthchecks, but you can add it to your compose

**Comment by LostOnTheLine** [comment]
> As an org, we don't add healthchecks, but you can add it to your compose

I've been trying to, but I can't get one that works properly. That's why I wasn't asking for it to be added to the Dockerfile, but instructions added for adding it in the compose.

**Comment by LostOnTheLine** [comment]
As this isn't _**"Done"**_ or **_"Completed"_** it should _NOT_ be marked as such. If you are not going to do it mark it as `"Wont Fix"` or `"Rejected"` instead

**Comment by aptalca** [comment]
Take that up with Github as all I did was `close`, because as stated in my closing comment, we won't do it.

**Comment by LostOnTheLine** [comment]
All I know is that other issues are marked as `"Won't Fix"` or `"Rejected"` while this one says `"1 task done"` & `"Completed"`. But **no** tasks were _done_ & nothing was _completed_. 

I don't know how the backend works but find it hard to believe that those are automatically applied by closing an issue. The `"Completed"` I could understand as the default, but marking a task as done doesn't even make sense.

You deciding you are not doing it is whatever, I don't generally expect support from linuxserver containers anyway, so that's more or less what I expected from official support, & I appreciate that you said as much at least. I was more hoping **other _users_** seeing it might comment with a solution rather than support from linuxserver officially. But it being marked as _`"Completed"`_ makes that less likely

**Comment by aptalca** [comment]
I have not "marked" anything as `completed`. I "closed" the issue.
We do not mark anything as `Rejected`. We don't even have a `rejected` label. There is a `wontfix` label, but it doesn't apply here, because there is nothing to fix as nothing is broken; and as you put it, this was a feature request.

I understand your feelings are hurt because we decided not to honor your request. However your attempts to have the last word in are bordering on trolling. Please stop. This is an official warning. You have veered way off topic.

If you're confused about why Github is showing a message `aptalca closed this as completed 5 hours ago`, take it up with Github as I posted earlier. We did not do that.

**Comment by aptalca** [comment]
OK, I've been informed Github recently added different closing options for issues. Clicking on `Close Issue` apparently closes it as completed. But if you click on the arrow next to it, there is another option. So apologies on that front.

**Comment by damiarita** [comment]
Hi,

I found this post looking for a healthcheck too. I eventually created one myself. So, I thought I would share it in case other people find this interesting.

Instead of checking the IP address, I look at the log file. To see if it changes or not. The main reason is that you may have the correct IP on DuckDNS while the container is not working. At least in my house, the IP address does not change very often. So, the system in the container con break and that would not be detectable by checking if DuckDNS has the correct IP.

Of course, this healthcheck depends on the log being created. So, make sure you pass the environment variable `LOG_FILE=true`

This is the Dockerfile I use where I have added the healthcheck:

```
FROM lscr.io/linuxserver/duckdns:b1648298-ls40
HEALTHCHECK CMD [[  $(($(date +%s) - $(stat --format=%Y /config/duck.log))) -gt 590 ]] &&  exit 1 ||  exit 0
```

Of course, you can choose whatever version in your Dockerfile

What the healthcheck does is 

- Getting the current time stamp in seconds: `$(date +%s) `
- Getting the last file modification time stamps in seconds: `$(stat --format=%Y /config/duck.log))`
-Substracting them and checking if the "age" of the log file is above 590 (the cron job runs every 5mins=300s and adds a random sleep of up to 289s).

Hope it helps!

**Comment by janusn** [comment]
> Hi,
> 
> I found this post looking for a healthcheck too. I eventually created one myself. So, I thought I would share it in case other people find this interesting.
> 
> Instead of checking the IP address, I look at the log file. To see if it changes or not. The main reason is that you may have the correct IP on DuckDNS while the container is not working. At least in my house, the IP address does not change very often. So, the system in the container con break and that would not be detectable by checking if DuckDNS has the correct IP.
> 
> Of course, this healthcheck depends on the log being created. So, make sure you pass the environment variable `LOG_FILE=true`
> 
> This is the Dockerfile I use where I have added the healthcheck:
> 
> ```
> FROM lscr.io/linuxserver/duckdns:b1648298-ls40
> HEALTHCHECK CMD [[  $(($(date +%s) - $(stat --format=%Y /config/duck.log))) -gt 590 ]] &&  exit 1 ||  exit 0
> ```
> 
> Of course, you can choose whatever version in your Dockerfile
> 
> What the healthcheck does is
> 
> * Getting the current time stamp in seconds: `$(date +%s) `
> * Getting the last file modification time stamps in seconds: `$(stat --format=%Y /config/duck.log))`
>   -Substracting them and checking if the "age" of the log file is above 590 (the cron job runs every 5mins=300s and adds a random sleep of up to 289s).
> 
> Hope it helps!

It works on mine. Thanks a ton!
